apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 3 
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: gcr.io/wh-host/hello:1.0.0
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "200Mi"
            cpu: "100m"
          requests:
            memory: "200Mi"
            cpu: "100m"

