apiVersion: batch/v1
kind: Job
metadata:
  name: abtest
spec:
  template:
    spec:
      containers:
      - name: abtest
        image: gcr.io/wh-host/abtest:2.0
        command: ["ab", "-c", "3",  "-r",  "-n",  "40000000",  "http://hello-svc/"]
      restartPolicy: Never
  backoffLimit: 4
